swagger: '2.0'
info:
  title: shurenyun API
  description: "数人云 API 文档(内部)"
  version: "3"
host: api.shurenyun.com
schemes:
  - https
basePath: /api/v3
produces:
  - application/json
paths:
  '/clusters/{cluster_id}/ports':
    get:
      summary: 获取集群被占用端口
      description: 获取集群被占用端口
      tags:
        - Internal
      parameters:
        - name: Authorization
          in: header
          description: 当前用户的 token
          required: true
          type: string
        - name: cluster_id
          in: path
          description: 集群Id
          required: true
          type: integer
      responses:
        '200':
          description: "正常：返回成功.<br>异常：集群不存在10017;数据异常10001;应用不存在14001"
          schema:
            type: object
            required:
              - code
              - data
            properties:
              code:
                type: integer
                format: int32
              data:
                type: array
                items:
                  $ref: '#/definitions/Ports'
        '401':
          description: 异常：token不合法时返回10002
          schema:
            $ref: '#/definitions/TokenNotValid'

  '/clusters/{cluster_id}/apps/{app_id}/logpaths':
    get:
      summary: 获取应用对应的日志文件
      description: 获取应用对应的日志文件
      tags:
        - Internal
      parameters:
        - name: Authorization
          in: header
          description: 当前用户的 token
          required: true
          type: string
        - name: cluster_id
          in: path
          description: 集群Id
          required: true
          type: integer
        - name: app_id
          in: path
          description: 应用Id
          required: true
          type: integer
      responses:
        '200':
          description: "正常：返回成功.<br>异常：集群不存在10017;数据异常10001;应用不存在14001"
          schema:
            type: object
            required:
              - code
              - data
            properties:
              code:
                type: integer
                format: int32
              data:
                type: array
                items:
                  $ref: '#/definitions/LogEntry'
        '401':
          description: 异常：token不合法时返回10002
          schema:
            $ref: '#/definitions/TokenNotValid'
definitions:
  TokenNotValid:
    type: object
    properties:
      code:
        type: integer
        format: int32
        description: 错误码，token验证失败为10002
  Ports:
    type: object
    required:
      - innerPorts
      - outerPorts
    properties:
      innerPorts:
        description: 内部占用端口
        type: array
        items:
          type: integer
      outerPorts:
        description: 外部占用端口
        type: array
        items:
          type: integer
  LogEntry:
    type: object
    properties:
      app_id:
        description: 应用对应的Id
        type: integer
      version_id:
        description: 版本Id
        type: integer
      filename:
        description: 日志文件名称，绝对路径
        type: string
